#!/bin/sh
#
#
# PROVIDE: serviio
# REQUIRE: DAEMON 
#
# Add the following lines to /etc/rc.conf to enable this service:
#
# serviio_enable:            Set to NO by default. Set it to YES to enable it.
#                            a path.
# serviio_user:              The user account serviio daemon runs as
#

. /etc/rc.subr

name="serviio"
rcvar=${name}_enable

pidfile=/var/run/serviio.pid
command=/usr/pbi/serviio-$(uname -m)/sbin/serviiod

#load_rc_config ${name}
load_rc_config $name

serviio_user=${serviio_user-"dlna"}

_dirs="/var/db/serviio /var/log/serviio"
#start_precmd="mkdir -p $_dirs; chown $serviio_user $_dirs"
command_args="$serviio_args &"

serviio_stop()
{
        res=1
        echo -n 'Stopping serviio.'
        if [ -f "${pidfile}" ]
        then
                kill -KILL $(cat "${pidfile}")
                rm -f ${pidfile}
                res=$?
        else
                killall -KILL serviiod
                res=$?
        fi

        echo
        return ${res}
}

stop_cmd='serviio_stop'
run_rc_command "$1"

# Hack to write proper pidfile for serviio
sleep 2
pgrep -U dlna -f org.serviio.MediaServer > /var/run/serviio.pid
